# Generated by Django 3.1.3 on 2023-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='date_enregistrement',
            new_name='date_registry',
        ),
        migrations.RenameField(
            model_name='banners',
            old_name='sub_titre',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='banners',
            old_name='titre',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='categorie',
        ),
    ]
