# Generated by Django 3.1.3 on 2023-06-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20230627_1445'),
        ('products', '0002_auto_20230627_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Nom categorie'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
