# Generated by Django 3.2.8 on 2023-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banners_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
