# Generated by Django 3.2.5 on 2023-09-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230912_1103'),
        ('banners', '0003_banners_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='category',
        ),
        migrations.AddField(
            model_name='banners',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.event', verbose_name='Nom categorie'),
        ),
    ]
