# Generated by Django 3.2.5 on 2023-09-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_variantes_options'),
        ('banners', '0004_auto_20230912_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.event', verbose_name='Evenement'),
        ),
    ]
