# Generated by Django 3.2 on 2023-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorited_by', to='products.Products'),
        ),
    ]
