# Generated by Django 3.2 on 2023-08-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_favorite_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_products',
        ),
    ]
