# Generated by Django 3.1.3 on 2023-06-27 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='date_enregistrement',
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='date_enregistrement',
        ),
        migrations.AddField(
            model_name='mailing',
            name='date_registry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletters',
            name='date_registry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Etat'),
        ),
    ]
