# Generated by Django 3.2.8 on 2023-07-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20230710_1340'),
        ('newsletters', '0002_auto_20230715_2338'),
    ]

    operations = [
    ]
