# Generated by Django 3.2.5 on 2023-12-15 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_alter_products_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=12, unique=True, verbose_name='reference commande')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='prix commande')),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('etat_commande', models.CharField(blank=True, default='EN COURS', max_length=200, null=True, verbose_name='etat de la commande')),
                ('date_registry', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True, verbose_name='Etat')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=12, unique=True, verbose_name='transaction ID')),
                ('amount', models.CharField(default='0', max_length=200, verbose_name='prix Commande')),
                ('currency', models.CharField(blank=True, default='XOF', max_length=200, null=True, verbose_name='Devise de la monnaie')),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Methode de payement')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description de la transaction')),
                ('metadata', models.CharField(blank=True, default='ABIDJAN', max_length=200, null=True, verbose_name='Autre info de payment')),
                ('operator_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Operator')),
                ('payment_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Date de payement')),
                ('status', models.CharField(blank=True, default='EN COURS', max_length=20, null=True, verbose_name='Satus Transaction')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.commandes', verbose_name='commande concerné')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProduitsCommandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unitaire', models.PositiveIntegerField(default=0, verbose_name='prix produit')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total du produit')),
                ('date_registry', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=False, verbose_name='Etat')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.commandes', verbose_name='commande concerné')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Produit')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variantes', verbose_name='variante choisie')),
            ],
            options={
                'verbose_name': 'Produit Commandé',
                'verbose_name_plural': 'Produits Commandés',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registry', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=False, verbose_name='Etat')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Produit favoris',
                'verbose_name_plural': 'Produits favoris',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='commandes',
            name='products',
            field=models.ManyToManyField(through='purchases.ProduitsCommandes', to='products.Products'),
        ),
        migrations.AddField(
            model_name='commandes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
    ]
