# Generated by Django 3.2.5 on 2023-12-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsCommandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=12, unique=True, verbose_name='transaction ID')),
                ('amount', models.CharField(default='0', max_length=200, verbose_name='prix Commande')),
                ('currency', models.CharField(blank=True, default='XOF', max_length=200, null=True, verbose_name='Devise de la monnaie')),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Methode de payement')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description de la transaction')),
                ('metadata', models.CharField(blank=True, default='ABIDJAN', max_length=200, null=True, verbose_name='Autre info de payment')),
                ('operator_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Operator')),
                ('payment_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Date de payement')),
                ('status', models.CharField(blank=True, default='EN COURS', max_length=20, null=True, verbose_name='Satus Transaction')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.commandes', verbose_name='commande concerné')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
            },
        ),
    ]
