# Generated by Django 3.1.3 on 2023-06-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230627_1445'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandes',
            old_name='date_enregistrement',
            new_name='date_registry',
        ),
        migrations.RenameField(
            model_name='produitscommandes',
            old_name='date_enregistrement',
            new_name='date_registry',
        ),
        migrations.RenameField(
            model_name='produitscommandes',
            old_name='prix_produit',
            new_name='price_product',
        ),
        migrations.RemoveField(
            model_name='produitscommandes',
            name='produit',
        ),
        migrations.AddField(
            model_name='produitscommandes',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='produitscommandes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produitscommandes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Etat'),
        ),
    ]
