# Generated by Django 3.2 on 2023-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20230801_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitscommandes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
