# Generated by Django 3.2.5 on 2023-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_transactionscommandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='localisation',
            field=models.BooleanField(default=True, verbose_name='Localisation'),
        ),
    ]
