# Generated by Django 3.2.8 on 2023-08-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_commandes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandes',
            old_name='total_montant',
            new_name='total_amount',
        ),
    ]
