# Generated by Django 3.2.5 on 2023-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_favoriteproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='prix commande'),
        ),
        migrations.AlterField(
            model_name='produitscommandes',
            name='price_unitaire',
            field=models.PositiveIntegerField(default=0, verbose_name='prix produit'),
        ),
    ]
