# Generated by Django 3.2 on 2023-08-09 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_rename_total_montant_commandes_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='date_commande',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandes',
            name='etat_commande',
            field=models.CharField(blank=True, default='En cours', max_length=200, null=True, verbose_name='etat de la commande'),
        ),
    ]
