# Generated by Django 3.2.8 on 2023-08-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_commandes_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='etat_commande',
            field=models.CharField(blank=True, default='En cours', max_length=200, null=True, verbose_name='etat de la commande'),
        ),
    ]
