# Generated by Django 3.2.5 on 2023-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20230811_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='reference',
            field=models.CharField(max_length=8, unique=True, verbose_name='reference commande'),
        ),
    ]
