# Generated by Django 3.2.5 on 2023-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_commandes_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='reference',
            field=models.CharField(max_length=12, unique=True, verbose_name='reference commande'),
        ),
    ]
