# Generated by Django 3.2.5 on 2023-09-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_descriptionprecise_slug'),
        ('purchases', '0006_alter_commandes_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitscommandes',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variantes', verbose_name='variante choisie'),
        ),
    ]
