# Generated by Django 3.2.5 on 2023-09-15 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_produitscommandes_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='date_registry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
    ]
