# Generated by Django 3.2.5 on 2023-11-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-id'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
