# Generated by Django 3.2.8 on 2023-06-25 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom categorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.image_categories, validators=[products.models.taille_image], verbose_name='Image')),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='titre evenement')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='date fin evenement')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='description evenement')),
                ('images', models.ImageField(blank=True, null=True, upload_to=products.models.image_evenements, verbose_name='Image')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True, verbose_name='Etat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SousCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom sous-categorie')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Nom categorie')),
            ],
            options={
                'verbose_name': 'Sous Categorie',
                'verbose_name_plural': 'Sous Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom produit')),
                ('extras', models.CharField(blank=True, max_length=200, null=True, verbose_name='Extras')),
                ('prix', models.IntegerField(blank=True, null=True, verbose_name='Prix')),
                ('prix_promo', models.IntegerField(blank=True, null=True, verbose_name='Prix evenement')),
                ('images', models.ImageField(blank=True, null=True, upload_to=products.models.image_produits, verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description produit')),
                ('description_precise', models.TextField(blank=True, null=True, verbose_name='description precise')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True, verbose_name='Etat')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Nom categorie')),
                ('evenement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.evenements', verbose_name='Evenement')),
                ('sous_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.souscategories', verbose_name='Nom sous categorie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='description evenement')),
                ('note', models.IntegerField(blank=True, null=True, verbose_name='Note produit')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True, verbose_name='Etat')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.produits', verbose_name='produit concerne')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-id'],
            },
        ),
    ]
