# Generated by Django 3.1.3 on 2023-06-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20230627_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20230627_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produits',
        ),
        migrations.DeleteModel(
            name='SousCategories',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Nom categorie'),
        ),
        migrations.AddField(
            model_name='products',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.event', verbose_name='Evenement'),
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(to='products.Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Nom sous categorie'),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur'),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='produit concerne'),
        ),
    ]
