# Generated by Django 3.2 on 2023-08-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaires',
            old_name='user',
            new_name='client',
        ),
    ]
