# Generated by Django 3.2.5 on 2023-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantes',
            name='quantite_en_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='quantité en stock'),
        ),
        migrations.AddField(
            model_name='variantes',
            name='reference',
            field=models.CharField(default='457DF574', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='contenu',
            field=models.TextField(blank=True, null=True, verbose_name='texte commentaire'),
        ),
    ]
