# Generated by Django 3.2.5 on 2023-07-17 18:02

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230710_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Image produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, validators=[products.models.taille_image], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='event',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.event', verbose_name='Evenement'),
        ),
    ]
