# Generated by Django 3.2.8 on 2023-07-16 02:17

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, validators=[products.models.taille_image], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='event',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.event', verbose_name='Evenement'),
        ),
    ]
