# Generated by Django 3.2.5 on 2023-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230729_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sous titre evenement'),
        ),
    ]
