# Generated by Django 3.2.8 on 2023-09-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_commentaires_date_registry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaires',
            options={'ordering': ['-id'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires Recents'},
        ),
    ]
