# Generated by Django 3.2.8 on 2023-07-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230710_1340'),
        ('products', '0006_auto_20230716_0317'),
    ]

    operations = [
    ]
