# Generated by Django 3.2.5 on 2023-09-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_commentaires_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantes',
            options={'ordering': ['-id'], 'verbose_name': 'Stock produit', 'verbose_name_plural': 'Stock Produits'},
        ),
    ]
