# Generated by Django 3.2.5 on 2023-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_variantes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantes',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom variante'),
        ),
    ]
