# Generated by Django 3.1.3 on 2023-07-20 15:07

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230717_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_evenements, verbose_name='images'),
        ),
    ]
