# Generated by Django 3.2.5 on 2023-11-30 15:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_variantes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description produit'),
        ),
    ]
