# Generated by Django 3.1.3 on 2023-07-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230720_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom sous-categorie')),
                ('date_registry', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True, verbose_name='Etat')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='variantes',
            field=models.ManyToManyField(blank=True, null=True, to='products.Variantes', verbose_name='les variantes'),
        ),
    ]
