# Generated by Django 3.1.3 on 2023-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230727_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='variantes',
            field=models.ManyToManyField(blank=True, to='products.Variantes', verbose_name='les variantes'),
        ),
    ]
