# Generated by Django 3.1.3 on 2023-07-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230728_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='slug',
        ),
    ]
