# Generated by Django 3.2.8 on 2023-07-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230729_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sous titre evenement'),
        ),
    ]
