# Generated by Django 3.2 on 2023-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_variantes_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionPrecise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('valeur', models.CharField(blank=True, max_length=200, null=True, verbose_name='valeur')),
                ('date_registry', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True, verbose_name='Etat')),
            ],
            options={
                'verbose_name': 'Description precise',
                'verbose_name_plural': 'Descriptions precises',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_precise',
        ),
        migrations.AddField(
            model_name='products',
            name='description_precise',
            field=models.ManyToManyField(blank=True, to='products.DescriptionPrecise', verbose_name='description precise'),
        ),
    ]
