# Generated by Django 3.2 on 2023-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20230804_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='event',
        ),
        migrations.AddField(
            model_name='products',
            name='event',
            field=models.ManyToManyField(blank=True, to='products.Event', verbose_name='Evenement'),
        ),
    ]
